/** 补充卡牌（金铲铲式扩展池） */
function mk(id, name, element, cls, rarity, stats, skills, extra = {}) {
  return {
    id, name, element, class: cls, rarity,
    description: extra.desc || `${name}——高阶幻兽`,
    baseHp: stats.hp, baseAttack: stats.atk, baseSpeed: stats.spd,
    baseDefense: stats.def, baseCritRate: stats.crit || 0.05, baseCritDamage: stats.cd || 2,
    levelMultipliers: [1, 1.2, 1.5, 2, 2.5],
    skills,
    costTier: extra.costTier,
    upgradeEvolution: extra.evo,
  };
}

const dmg = (amount, cd = 2) => ({
  id: `${amount}_dmg`, name: '打击', trigger: 'ON_ATTACK', target: 'ENEMY_LOWEST_HP',
  description: `造成${amount}伤害`, cooldown: cd, condition: null,
  effects: [{ type: 'DEAL_DAMAGE', target: 'ENEMY_LOWEST_HP', amount }],
});

export const CARD_DATA_EXTRA = [
  mk('sky_dragon', '天穹龙皇', 'wind', 'mage', 'legendary',
    { hp: 95, atk: 16, spd: 12, def: 4, crit: 0.12 },
    [dmg(22, 1), { id: 'sky_burst', name: '天穹裂空', trigger: 'TURN_START', target: 'ENEMY_ALL',
      description: '对所有敌人造成12法术伤害', cooldown: 3, condition: null,
      effects: [{ type: 'DEAL_DAMAGE', target: 'ENEMY_ALL', amount: 12 }] }],
    { costTier: 5, desc: '五费传说，三星后统治战场', evo: { skillId: 'sky_burst', replaceDamage: 28, desc: '天穹裂空造成28伤害 ★3' } }),

  mk('void_sovereign', '虚空主宰', 'dark', 'assassin', 'legendary',
    { hp: 78, atk: 20, spd: 16, def: 3, crit: 0.18 },
    [dmg(26, 1), { id: 'void_exec', name: '虚空处决', trigger: 'ON_KILL', target: 'SELF',
      description: '击杀后攻速提升', cooldown: 0, condition: null,
      effects: [{ type: 'BUFF', target: 'SELF', stat: 'speed', value: 4, duration: 2 }] }],
    { costTier: 5, evo: { skillId: 'void_exec', spdBuffBonus: 6, desc: '击杀后速度+10 ★3' } }),

  mk('saint_unicorn', '圣光独角兽', 'light', 'support', 'legendary',
    { hp: 88, atk: 10, spd: 11, def: 5 },
    [{ id: 'holy_wave', name: '圣愈波', trigger: 'TURN_START', target: 'TEAM_ALL',
      description: '全队回复8生命', cooldown: 2, condition: null,
      effects: [{ type: 'HEAL', target: 'TEAM_ALL', amount: 8 }] }],
    { costTier: 5, evo: { skillId: 'holy_wave', healBonus: 12, desc: '圣愈波回复20 ★3' } }),

  mk('thunder_titan', '雷霆泰坦', 'electric', 'warrior', 'legendary',
    { hp: 110, atk: 14, spd: 8, def: 8 },
    [dmg(18, 1), { id: 'thunder_roar', name: '雷霆咆哮', trigger: 'BATTLE_START', target: 'ENEMY_ALL',
      description: '开战眩晕敌人1回合', cooldown: 0, condition: null,
      effects: [{ type: 'APPLY_STATUS', target: 'ENEMY_ALL', status: 'STUN', duration: 1, value: 0 }] }],
    { costTier: 5 }),

  mk('crystal_golem', '晶岩巨像', 'earth', 'tank', 'epic',
    { hp: 100, atk: 8, spd: 5, def: 12 },
    [{ id: 'crystal_wall', name: '晶岩壁垒', trigger: 'BATTLE_START', target: 'SELF',
      description: '获得25护盾', cooldown: 0, condition: null,
      effects: [{ type: 'SHIELD', target: 'SELF', amount: 25 }] }],
    { costTier: 4 }),

  mk('storm_ranger', '风暴游侠', 'wind', 'archer', 'epic',
    { hp: 62, atk: 15, spd: 14, def: 3, crit: 0.14 },
    [dmg(16, 1), { id: 'pierce_shot', name: '穿云箭', trigger: 'ON_ATTACK', target: 'ENEMY_LOWEST_HP',
      description: '攻击附加6伤害', cooldown: 1, condition: null,
      effects: [{ type: 'DEAL_DAMAGE', target: 'ENEMY_LOWEST_HP', amount: 6 }] }],
    { costTier: 4 }),

  mk('tide_guardian', '潮汐守卫', 'water', 'guardian', 'epic',
    { hp: 92, atk: 7, spd: 7, def: 10 },
    [{ id: 'tide_shield', name: '潮盾', trigger: 'ON_HIT', target: 'SELF',
      description: '受击获得8护盾', cooldown: 2, condition: null,
      effects: [{ type: 'SHIELD', target: 'SELF', amount: 8 }] }],
    { costTier: 4 }),

  mk('flame_dancer', '烈焰舞姬', 'fire', 'ranger', 'epic',
    { hp: 58, atk: 17, spd: 15, def: 2, crit: 0.15 },
    [dmg(17, 0), { id: 'flame_dash', name: '焰步', trigger: 'TURN_START', target: 'SELF',
      description: '速度+3', cooldown: 2, condition: null,
      effects: [{ type: 'BUFF', target: 'SELF', stat: 'speed', value: 3, duration: 1 }] }],
    { costTier: 4 }),

  mk('vine_shaman', '蔓藤萨满', 'grass', 'support', 'rare',
    { hp: 52, atk: 6, spd: 9, def: 4 },
    [{ id: 'vine_heal', name: '蔓生治愈', trigger: 'TURN_START', target: 'TEAM_LOWEST_HP',
      description: '治疗最低血友方10', cooldown: 2, condition: null,
      effects: [{ type: 'HEAL', target: 'TEAM_LOWEST_HP', amount: 10 }] }]),

  mk('iron_hound', '钢铁猎犬', 'earth', 'ranger', 'rare',
    { hp: 48, atk: 11, spd: 13, def: 3, crit: 0.1 },
    [dmg(11, 1)]),

  mk('spark_fox', '闪雷狐', 'electric', 'assassin', 'rare',
    { hp: 40, atk: 12, spd: 16, def: 2, crit: 0.16 },
    [dmg(13, 0)]),

  mk('dawn_knight', '晨曦骑士', 'light', 'guardian', 'rare',
    { hp: 65, atk: 8, spd: 8, def: 7 },
    [{ id: 'dawn_aegis', name: '晨曦庇护', trigger: 'BATTLE_START', target: 'TEAM_ALL',
      description: '全队获得6护盾', cooldown: 0, condition: null,
      effects: [{ type: 'SHIELD', target: 'TEAM_ALL', amount: 6 }] }]),

  // —— 三费史诗（12 张）——
  mk('ember_knight', '炽焰骑士', 'fire', 'warrior', 'epic',
    { hp: 72, atk: 12, spd: 9, def: 6 },
    [dmg(14, 1), { id: 'ember_charge', name: '烈焰冲锋', trigger: 'BATTLE_START', target: 'SELF',
      description: '开战获得8攻', cooldown: 0, condition: null,
      effects: [{ type: 'BUFF', target: 'SELF', stat: 'attack', value: 8, duration: 2 }] }],
    { costTier: 3 }),

  mk('frost_mage', '霜寒术士', 'water', 'mage', 'epic',
    { hp: 48, atk: 14, spd: 10, def: 2 },
    [{ id: 'frost_bolt', name: '霜冻箭', trigger: 'BEFORE_ATTACK', target: 'FRONT_ENEMY',
      description: '18水伤+减速', cooldown: 2, condition: null,
      effects: [
        { type: 'DEAL_DAMAGE', target: 'FRONT_ENEMY', amount: 18, damageType: 'water' },
        { type: 'DEBUFF', target: 'FRONT_ENEMY', stat: 'speed', value: 4, duration: 2 },
      ] }],
    { costTier: 3 }),

  mk('thorn_assassin', '荆棘刺客', 'grass', 'assassin', 'epic',
    { hp: 44, atk: 16, spd: 15, def: 2, crit: 0.16 },
    [dmg(15, 0), { id: 'thorn_mark', name: '荆棘印记', trigger: 'ON_ATTACK', target: 'FRONT_ENEMY',
      description: '附加中毒', cooldown: 1, condition: null,
      effects: [{ type: 'APPLY_STATUS', target: 'FRONT_ENEMY', status: 'POISON', duration: 2, value: 5 }] }],
    { costTier: 3 }),

  mk('volt_stalker', '伏特追猎者', 'electric', 'assassin', 'epic',
    { hp: 46, atk: 15, spd: 16, def: 2, crit: 0.14 },
    [dmg(16, 0), { id: 'volt_chain', name: '电弧链', trigger: 'ON_KILL', target: 'ENEMY_LOWEST_HP',
      description: '击杀弹射8电伤', cooldown: 0, condition: null,
      effects: [{ type: 'DEAL_DAMAGE', target: 'ENEMY_LOWEST_HP', amount: 8, damageType: 'electric' }] }],
    { costTier: 3 }),

  mk('stone_bulwark', '磐石壁垒', 'earth', 'tank', 'epic',
    { hp: 88, atk: 7, spd: 6, def: 10 },
    [{ id: 'stone_skin', name: '岩肤', trigger: 'BATTLE_START', target: 'SELF',
      description: '获得18护盾', cooldown: 0, condition: null,
      effects: [{ type: 'SHIELD', target: 'SELF', amount: 18 }] }],
    { costTier: 3 }),

  mk('wind_blade', '疾风刃客', 'wind', 'assassin', 'epic',
    { hp: 42, atk: 17, spd: 17, def: 1, crit: 0.15 },
    [dmg(17, 0), { id: 'wind_step', name: '风步', trigger: 'TURN_START', target: 'SELF',
      description: '速度+4', cooldown: 2, condition: null,
      effects: [{ type: 'BUFF', target: 'SELF', stat: 'speed', value: 4, duration: 1 }] }],
    { costTier: 3 }),

  mk('light_acolyte', '圣光侍者', 'light', 'support', 'epic',
    { hp: 56, atk: 8, spd: 10, def: 4 },
    [{ id: 'holy_mend', name: '圣愈', trigger: 'TURN_START', target: 'TEAM_LOWEST_HP',
      description: '治疗最低血友方12', cooldown: 2, condition: null,
      effects: [{ type: 'HEAL', target: 'TEAM_LOWEST_HP', amount: 12 }] }],
    { costTier: 3 }),

  mk('shadow_stalker', '影袭者', 'dark', 'assassin', 'epic',
    { hp: 44, atk: 17, spd: 14, def: 2, crit: 0.17 },
    [dmg(18, 0), { id: 'shadow_strike', name: '暗影突袭', trigger: 'BEFORE_ATTACK', target: 'LOWEST_HP_ENEMY',
      description: '对最低血敌人额外10暗伤', cooldown: 2, condition: null,
      effects: [{ type: 'DEAL_DAMAGE', target: 'LOWEST_HP_ENEMY', amount: 10, damageType: 'dark' }] }],
    { costTier: 3 }),

  mk('flame_shaman', '烈焰萨满', 'fire', 'mage', 'epic',
    { hp: 50, atk: 15, spd: 9, def: 2 },
    [{ id: 'flame_wave', name: '焰浪', trigger: 'BEFORE_ATTACK', target: 'ALL_ENEMIES',
      description: '全体12火伤', cooldown: 3, condition: null,
      effects: [{ type: 'DEAL_DAMAGE', target: 'ALL_ENEMIES', amount: 12, damageType: 'fire' }] }],
    { costTier: 3 }),

  mk('coral_guard', '珊瑚守卫', 'water', 'guardian', 'epic',
    { hp: 78, atk: 8, spd: 8, def: 8 },
    [{ id: 'coral_aegis', name: '珊瑚盾', trigger: 'ON_HIT', target: 'SELF',
      description: '受击回复6生命', cooldown: 2, condition: null,
      effects: [{ type: 'HEAL', target: 'SELF', amount: 6 }] }],
    { costTier: 3 }),

  mk('bloom_singer', '花语歌者', 'grass', 'support', 'epic',
    { hp: 54, atk: 7, spd: 11, def: 3 },
    [{ id: 'bloom_chorus', name: '花语合唱', trigger: 'BATTLE_START', target: 'TEAM_ALL',
      description: '全队回复8生命', cooldown: 0, condition: null,
      effects: [{ type: 'HEAL', target: 'TEAM_ALL', amount: 8 }] }],
    { costTier: 3 }),

  // —— 四费史诗（12 张）——
  mk('abyss_horror', '深渊恐魔', 'dark', 'mage', 'epic',
    { hp: 68, atk: 16, spd: 10, def: 3 },
    [{ id: 'abyss_blast', name: '深渊冲击', trigger: 'BEFORE_ATTACK', target: 'ALL_ENEMIES',
      description: '全体16暗伤', cooldown: 3, condition: null,
      effects: [{ type: 'DEAL_DAMAGE', target: 'ALL_ENEMIES', amount: 16, damageType: 'dark' }] }],
    { costTier: 4 }),

  mk('solar_crusader', '烈阳圣骑', 'light', 'guardian', 'epic',
    { hp: 98, atk: 11, spd: 8, def: 9 },
    [{ id: 'solar_bless', name: '烈阳祝福', trigger: 'BATTLE_START', target: 'TEAM_ALL',
      description: '全队获得12护盾', cooldown: 0, condition: null,
      effects: [{ type: 'SHIELD', target: 'TEAM_ALL', amount: 12 }] }],
    { costTier: 4 }),

  mk('storm_breaker', '风暴破阵者', 'wind', 'warrior', 'epic',
    { hp: 88, atk: 14, spd: 11, def: 6 },
    [dmg(16, 1), { id: 'storm_cleave', name: '风暴斩', trigger: 'ON_ATTACK', target: 'ALL_ENEMIES',
      description: '攻击溅射6风伤', cooldown: 2, condition: null,
      effects: [{ type: 'DEAL_DAMAGE', target: 'ALL_ENEMIES', amount: 6, damageType: 'wind' }] }],
    { costTier: 4 }),

  mk('inferno_colossus', '炼狱巨兽', 'fire', 'tank', 'epic',
    { hp: 115, atk: 10, spd: 6, def: 11 },
    [{ id: 'inferno_shell', name: '炼狱甲壳', trigger: 'BATTLE_START', target: 'SELF',
      description: '获得30护盾并反伤', cooldown: 0, condition: null,
      effects: [
        { type: 'SHIELD', target: 'SELF', amount: 30 },
        { type: 'APPLY_STATUS', target: 'SELF', status: 'THORNS', duration: 99, value: 8 },
      ] }],
    { costTier: 4 }),
];
