/** 净化远征 · 战斗事件类型（驱动 VFX / 音效） */
export const COMBAT_EVENT = {
  CARD_PLAYED: 'CARD_PLAYED',
  BLOCK_GAIN: 'BLOCK_GAIN',
  HEAL: 'HEAL',
  DRAW: 'DRAW',
  DAMAGE: 'DAMAGE',
  POISON: 'POISON',
  ENEMY_ACTION: 'ENEMY_ACTION',
  BUFF: 'BUFF',
  DEBUFF: 'DEBUFF',
  TURN_END: 'TURN_END',
  TURN_START: 'TURN_START',
  HAND_DISCARDED: 'HAND_DISCARDED',
  COMBAT_WON: 'COMBAT_WON',
  COMBAT_LOST: 'COMBAT_LOST',
};
